import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import HeaderMenu from '@/components/HeaderMenu'
import SectionOne from '@/components/SectionOne';
import SectionTwo from '../components/SectionTwo';
import SectionThree from '../components/SectionThree';
import { useEffect, useState } from 'react';

export default function Home() {

  const saveSection = (section: string) => {
    localStorage.setItem('currentSection', section)
  }

  const getSavedSection = () => {
    const savedSection = localStorage.getItem('currentSection')
    return savedSection
  }

  const scrollTop = () => {
    // console.log('scrollTop currentSection: ', getSavedSection())
    const currentSection = getSavedSection()
      if (currentSection === 'secondLocator') {
        saveSection('firstLocator')
        handleSectionToScroll('firstLocator')
      }

      if (currentSection === 'thirdLocator') {
        saveSection('secondLocator')
        handleSectionToScroll('secondLocator')
      }
  }
  
  const scrollDown = () => {
    const currentSection = getSavedSection()
    // console.log('scrollDown currentSection: ', currentSection)

      if (currentSection === 'firstLocator') {
        saveSection('secondLocator')
        handleSectionToScroll('secondLocator')
      }

      if (currentSection === 'secondLocator') {
        saveSection('thirdLocator')
        handleSectionToScroll('thirdLocator')
      }
  }

  const handleSectionToScroll = (section: string) => {
    const firstLocator:any = document.querySelector("#s1");
    const secondLocator:any = document.querySelector("#s2");
    const thirdLocator:any = document.querySelector("#s3");

    const locatorsAvailable:any = {firstLocator, secondLocator, thirdLocator}
    
    locatorsAvailable[section].scrollIntoView({ behavior: "smooth", block: "end", inline: "nearest", offset: -1000});
  }

  useEffect(() => {
    const savedSection = localStorage.getItem('currentSection')

    if (savedSection === null) {
      saveSection('firstLocator')
    } else {
      handleSectionToScroll(savedSection)
    }
  }, [])

  const handleScroll = (e: any) => {
    if (e.wheelDelta === 120) {
      // console.log('scrollUp');
      scrollTop();
    } else {
      // console.log('scrollDown');
      scrollDown();
    }
  };

  // useEffect(() => {
  //   window.addEventListener('mousewheel', handleScroll);
  //   return () => {
  //     window.removeEventListener('mousewheel', handleScroll);
  //   };
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderMenu />

        <div className={styles.containerSections}>
          <SectionOne />
          <SectionTwo />
          <SectionThree />
        </div>

      </main>
    </>
  )
}


